# Generated by Django 5.0.14 on 2026-06-30 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('dark_mode', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolarCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_bill', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('three_year', models.DecimalField(decimal_places=2, max_digits=12)),
                ('five_year', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ten_year', models.DecimalField(decimal_places=2, max_digits=12)),
                ('twenty_year', models.DecimalField(decimal_places=2, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=2, help_text='Return on Investment %', max_digits=5)),
                ('break_even', models.DecimalField(decimal_places=2, help_text='Break even period in years', max_digits=5)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carbon_saved', models.DecimalField(decimal_places=2, help_text='Tons of CO2', max_digits=10)),
                ('trees_saved', models.IntegerField()),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('future_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
