# Generated by Django 5.2.15 on 2026-07-01 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_solarcalculation_fifteen_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('rate_per_kwh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='solarcalculation',
            name='fifteen_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('tax_id', models.CharField(blank=True, help_text='Aadhaar / Tax ID', max_length=50, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='solar.client')),
            ],
        ),
        migrations.CreateModel(
            name='SolarPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=50, unique=True)),
                ('capacity_kw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('installation_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('solar_panel_brand', models.CharField(max_length=100)),
                ('inverter_brand', models.CharField(max_length=100)),
                ('number_of_panels', models.IntegerField()),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_period_months', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='solar.client')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month of the payment (usually 1st day of month)')),
                ('exported_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tariff_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maintenance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='solar.client')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='solar.solarplant')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('daily_generation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_generation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_generation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lifetime_generation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('self_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='solar.solarplant')),
            ],
        ),
    ]
