# Generated by Django 5.2.15 on 2026-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_tariff_alter_solarcalculation_fifteen_year_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='electricity_exported',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculated automatically', max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='gross_revenue',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='maintenance_charge',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_earnings',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
