# Generated by Django 5.2.15 on 2026-07-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_solarcalculation_sim_maint_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarcalculation',
            name='sim_maint_pct',
        ),
        migrations.AddField(
            model_name='solarcalculation',
            name='sim_maint_val',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
